<?php
namespace App\Http\Controllers;
use App\Models\House; use App\Models\Region; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class PublicApiController extends Controller {
 public function regions(){return response()->json(['data'=>Region::where('is_active',true)->orderBy('level')->orderBy('name')->get(['id','parent_id','code','name','type','level'])]);}
 public function rtlh(Request $r){$q=House::with(['region','structure','floor','ceiling','wall','roof','sanitation','utility'])->where('is_public',true)->whereIn('status',['verified','published']);$q->when($r->filled('region_id'),fn($x)=>$x->where('region_id',$r->integer('region_id')));$q->when($r->filled('year'),fn($x)=>$x->where('survey_year',$r->integer('year')));$rows=$q->paginate(min(max($r->integer('per_page',50),1),500));$rows->getCollection()->transform(fn($h)=>$this->publicHouse($h));return response()->json($rows);}
 public function show(House $house){abort_unless($house->is_public&&in_array($house->status,['verified','published'],true),404);$house->load(['region','structure','floor','ceiling','wall','roof','sanitation','utility','latestAssessment']);return response()->json(['data'=>$this->publicHouse($house,true)]);}
 public function statistics(){ $q=House::where('is_public',true)->whereIn('status',['verified','published']);return response()->json(['total'=>(clone $q)->count(),'by_year'=>(clone $q)->selectRaw('survey_year,count(*) total')->groupBy('survey_year')->orderBy('survey_year')->get(),'by_status'=>(clone $q)->selectRaw('status,count(*) total')->groupBy('status')->get()]);}
 private function publicHouse(House $h,bool $detail=false):array{ $a=['id'=>$h->id,'house_code'=>$h->house_code,'region'=>$h->region?->only(['id','code','name','type']),'area_m2'=>$h->area_m2,'survey_year'=>$h->survey_year,'status'=>$h->status];$coord=DB::selectOne('SELECT ST_X(location) AS lng, ST_Y(location) AS lat FROM houses WHERE id = ?',[$h->id]);$a['coordinates']=$coord?[(float)$coord->lng,(float)$coord->lat]:null;if($detail){$a['structure']=$h->structure;$a['floor']=$h->floor;$a['ceiling']=$h->ceiling;$a['wall']=$h->wall;$a['roof']=$h->roof;$a['sanitation']=$h->sanitation;$a['utility']=$h->utility;$a['latest_assessment']=$h->latestAssessment;}return $a;}
}
